// src/pages/Home.jsx
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PageTransition } from '../components/layout';
import { Button, ProjectCard } from '../components/ui';
import { FloatingShapes } from '../components/three';
import { getFeaturedProjects } from '../data/projects';

const featuredProjects = getFeaturedProjects();

export default function Home() {
  const [isAtTop, setIsAtTop] = useState(true);

  useEffect(() => {
    const handleScroll = () => {
      setIsAtTop(window.scrollY < 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <PageTransition>
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        <FloatingShapes />
        
        <div className="relative z-10 max-w-4xl mx-auto px-6 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <motion.p 
              className="text-accent-400 font-medium mb-4"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
            >
              Hi, I'm
            </motion.p>
            
            <h1 className="text-5xl md:text-7xl font-bold mb-6">
              <span className="gradient-text">Joel</span>
            </h1>
            
            <p className="text-xl md:text-2xl text-gray-400 mb-8 max-w-2xl mx-auto">
              A passionate developer crafting beautiful, interactive digital experiences
              with modern web technologies.
            </p>
            
            <div className="flex flex-wrap items-center justify-center gap-4">
              <Button to="/projects" size="lg">
                View My Work
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
                </svg>
              </Button>
              <Button to="/about" variant="secondary" size="lg">
                About Me
              </Button>
            </div>
          </motion.div>
          
          {/* Scroll indicator */}
          <AnimatePresence>
            {isAtTop && (
              <motion.div
                className="fixed bottom-8 left-1/2 -translate-x-1/2"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 10 }}
                transition={{ duration: 0.3 }}
              >
                <motion.div
                  animate={{ y: [0, 10, 0] }}
                  transition={{ duration: 2, repeat: Infinity }}
                  className="flex flex-col items-center gap-2 text-gray-500"
                >
                  <span className="text-sm">Scroll to explore</span>
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                  </svg>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </section>

      {/* Featured Projects Section */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Featured <span className="gradient-text">Projects</span>
            </h2>
            <p className="text-gray-400 max-w-2xl mx-auto">
              A selection of my favorite work. Each project represents a unique challenge
              and creative solution.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {featuredProjects.map((project, index) => (
              <ProjectCard key={project.id} project={project} index={index} />
            ))}
          </div>

          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4 }}
            className="text-center mt-12"
          >
            <Button to="/projects" variant="secondary">
              View All Projects
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
              </svg>
            </Button>
          </motion.div>
        </div>
      </section>

      {/* Skills Preview Section */}
      <section className="py-20 px-6 border-t border-white/5">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="glass rounded-3xl p-8 md:p-12"
          >
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h2 className="text-3xl font-bold mb-4">
                  Let's build something <span className="gradient-text">amazing</span>
                </h2>
                <p className="text-gray-400 mb-6">
                  I specialize in creating modern web applications with React, 
                  immersive 3D experiences with Three.js, and beautiful interfaces 
                  with cutting-edge CSS.
                </p>
                <Button to="/about">
                  Learn More About Me
                </Button>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                {['React', 'Three.js', 'TypeScript', 'Node.js'].map((skill, i) => (
                  <motion.div
                    key={skill}
                    initial={{ opacity: 0, scale: 0.8 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="glass rounded-xl p-4 text-center hover:bg-white/10 transition-colors"
                  >
                    <span className="font-medium">{skill}</span>
                  </motion.div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </PageTransition>
  );
}

// src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { InViewDirective } from '../../shared/directives/in-view.directive';
import { ButtonComponent } from '../../components/ui/button/button.component';
import { ProjectCardComponent } from '../../components/ui/project-card/project-card.component';
import { LavaLampBackgroundComponent } from '../../components/lava-lamp/lava-lamp-background.component';
import { getFeaturedProjects, Project } from '../../data/projects';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    InViewDirective,
    ButtonComponent,
    ProjectCardComponent,
    LavaLampBackgroundComponent,
  ],
  templateUrl: './home.component.html',
})
export class HomeComponent {
  featuredProjects: Project[] = getFeaturedProjects();
}

<!-- Hero Section -->
<section
  class="relative min-h-screen flex items-center justify-center overflow-hidden"
>
  <app-lava-lamp-background
    [color]="'#f97316'"
    [cursorBallColor]="'#fb923c'"
    [opacity]="0.6"
    [speed]="0.25"
    [ballCount]="10"
    [enableMouseInteraction]="true"
    [cursorBallSize]="3"
    [hoverSmoothness]="0.05"
  />

  <div class="relative z-10 max-w-4xl mx-auto px-6 text-center pointer-events-none">
    <div class="fade-in-up" appInView>
      <p class="text-accent-400 font-medium mb-4 fade-in-up" appInView [delay]="200">
        Hi, I'm
      </p>

      <h1 class="text-5xl md:text-7xl font-bold mb-6">
        <span class="gradient-text">Joel</span>
      </h1>

      <p class="text-xl md:text-2xl text-gray-400 mb-8 max-w-2xl mx-auto">
        A passionate developer crafting beautiful, interactive digital
        experiences with modern web technologies.
      </p>

      <div class="flex flex-wrap items-center justify-center gap-4 pointer-events-auto">
        <app-button to="/projects" size="lg">
          View My Work
          <svg
            class="w-5 h-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M14 5l7 7m0 0l-7 7m7-7H3"
            />
          </svg>
        </app-button>
        <app-button to="/about" variant="secondary" size="lg">
          About Me
        </app-button>
      </div>
    </div>
  </div>
</section>

<!-- Featured Projects Section -->
<section class="py-20 px-6">
  <div class="max-w-6xl mx-auto">
    <div class="text-center mb-12 fade-in-up" appInView>
      <h2 class="text-3xl md:text-4xl font-bold mb-4">
        Featured <span class="gradient-text">Projects</span>
      </h2>
      <p class="text-gray-400 max-w-2xl mx-auto">
        A selection of my favorite work. Each project represents a unique
        challenge and creative solution.
      </p>
    </div>

    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      @for (project of featuredProjects; track project.id; let i = $index) {
        <div class="fade-in-up" appInView [delay]="i * 100">
          <app-project-card [project]="project" />
        </div>
      }
    </div>

    <div class="text-center mt-12 fade-in-up" appInView [delay]="400">
      <app-button to="/projects" variant="secondary">
        View All Projects
        <svg
          class="w-4 h-4"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M14 5l7 7m0 0l-7 7m7-7H3"
          />
        </svg>
      </app-button>
    </div>
  </div>
</section>

<!-- Skills Preview Section -->
<section class="py-20 px-6 border-t border-white/5">
  <div class="max-w-6xl mx-auto">
    <div class="glass rounded-3xl p-8 md:p-12 fade-in-up" appInView>
      <div class="grid md:grid-cols-2 gap-8 items-center">
        <div>
          <h2 class="text-3xl font-bold mb-4">
            Let's build something
            <span class="gradient-text">amazing</span>
          </h2>
          <p class="text-gray-400 mb-6">
            I specialize in creating modern web applications with Angular,
            immersive WebGL experiences with OGL, and beautiful interfaces with
            cutting-edge CSS.
          </p>
          <app-button to="/about">Learn More About Me</app-button>
        </div>

        <div class="grid grid-cols-2 gap-4">
          @for (skill of ['Angular', 'WebGL', 'TypeScript', 'Node.js']; track skill; let i = $index) {
            <div
              class="glass rounded-xl p-4 text-center hover:bg-white/10 transition-colors fade-in-scale"
              appInView
              [delay]="i * 100"
            >
              <span class="font-medium">{{ skill }}</span>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</section>
