// src/pages/Projects.jsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PageTransition } from '../components/layout';
import { ProjectCard } from '../components/ui';
import { projects, categories, getProjectsByCategory } from '../data/projects';

export default function Projects() {
  const [activeCategory, setActiveCategory] = useState('All');
  const filteredProjects = getProjectsByCategory(activeCategory);

  return (
    <PageTransition>
      <section className="pt-32 pb-20 px-6">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center mb-12"
          >
            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              My <span className="gradient-text">Projects</span>
            </h1>
            <p className="text-gray-400 max-w-2xl mx-auto">
              Explore my portfolio of projects spanning web applications, games, 
              developer tools, and creative experiments.
            </p>
          </motion.div>

          {/* Category Filter */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="flex flex-wrap justify-center gap-2 mb-12"
          >
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => setActiveCategory(category)}
                className={`
                  relative px-5 py-2 rounded-xl text-sm font-medium transition-colors
                  ${activeCategory === category 
                    ? 'text-white' 
                    : 'text-gray-400 hover:text-white hover:bg-white/5'
                  }
                `}
              >
                {activeCategory === category && (
                  <motion.div
                    layoutId="category-active"
                    className="absolute inset-0 bg-accent-500/20 border border-accent-500/30 rounded-xl"
                    transition={{ type: 'spring', duration: 0.5 }}
                  />
                )}
                <span className="relative z-10">{category}</span>
              </button>
            ))}
          </motion.div>

          {/* Projects Grid */}
          <motion.div 
            layout
            className="grid md:grid-cols-2 lg:grid-cols-3 gap-6"
          >
            <AnimatePresence mode="popLayout">
              {filteredProjects.map((project, index) => (
                <motion.div
                  key={project.id}
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ duration: 0.3 }}
                >
                  <ProjectCard project={project} index={index} />
                </motion.div>
              ))}
            </AnimatePresence>
          </motion.div>

          {/* Empty State */}
          {filteredProjects.length === 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-20"
            >
              <p className="text-gray-500">No projects found in this category.</p>
            </motion.div>
          )}

          {/* Stats */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-20 grid grid-cols-2 md:grid-cols-4 gap-4"
          >
            {[
              { label: 'Total Projects', value: projects.length },
              { label: 'Web Apps', value: projects.filter(p => p.category === 'Web App').length },
              { label: 'Games', value: projects.filter(p => p.category === 'Game').length },
              { label: 'Tools & Other', value: projects.filter(p => ['Tool', 'Creative'].includes(p.category)).length },
            ].map((stat, i) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="glass rounded-2xl p-6 text-center"
              >
                <div className="text-3xl font-bold gradient-text mb-1">{stat.value}</div>
                <div className="text-sm text-gray-400">{stat.label}</div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>
    </PageTransition>
  );
}

// src/app/pages/projects/projects.component.ts
import { Component } from '@angular/core';
import { InViewDirective } from '../../shared/directives/in-view.directive';
import { ProjectCardComponent } from '../../components/ui/project-card/project-card.component';
import {
  projects,
  categories,
  getProjectsByCategory,
  Project,
} from '../../data/projects';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [InViewDirective, ProjectCardComponent],
  templateUrl: './projects.component.html',
})
export class ProjectsComponent {
  categories = categories;
  activeCategory = 'All';
  filteredProjects: Project[] = projects;
  allProjects = projects;

  stats = [
    { label: 'Total Projects', value: projects.length },
    { label: 'AI/ML', value: projects.filter((p) => p.category === 'AI/ML').length },
    { label: 'Web Apps', value: projects.filter((p) => p.category === 'Web App').length },
    {
      label: 'Games & Other',
      value: projects.filter((p) => ['Game', 'Tool', 'Creative'].includes(p.category)).length,
    },
  ];

  setCategory(category: string) {
    this.activeCategory = category;
    this.filteredProjects = getProjectsByCategory(category);
  }
}

<section class="pt-32 pb-20 px-6">
  <div class="max-w-6xl mx-auto">
    <!-- Header -->
    <div class="text-center mb-12 fade-in-up" appInView>
      <h1 class="text-4xl md:text-5xl font-bold mb-4">
        My <span class="gradient-text">Projects</span>
      </h1>
      <p class="text-gray-400 max-w-2xl mx-auto">
        Explore my portfolio of projects spanning web applications, games,
        developer tools, and creative experiments.
      </p>
    </div>

    <!-- Category Filter -->
    <div class="flex flex-wrap justify-center gap-2 mb-12 fade-in-up" appInView [delay]="200">
      @for (category of categories; track category) {
        <button
          (click)="setCategory(category)"
          class="relative px-5 py-2 rounded-xl text-sm font-medium transition-colors"
          [class]="activeCategory === category
            ? 'text-white bg-accent-500/20 border border-accent-500/30'
            : 'text-gray-400 hover:text-white hover:bg-white/5'"
        >
          {{ category }}
        </button>
      }
    </div>

    <!-- Projects Grid -->
    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      @for (project of filteredProjects; track project.id; let i = $index) {
        <div class="fade-in-scale" appInView [delay]="i * 100">
          <app-project-card [project]="project" />
        </div>
      }
    </div>

    <!-- Empty State -->
    @if (filteredProjects.length === 0) {
      <div class="text-center py-20">
        <p class="text-gray-500">No projects found in this category.</p>
      </div>
    }

    <!-- Stats -->
    <div class="mt-20 grid grid-cols-2 md:grid-cols-4 gap-4">
      @for (stat of stats; track stat.label; let i = $index) {
        <div
          class="glass rounded-2xl p-6 text-center fade-in-up"
          appInView
          [delay]="i * 100"
        >
          <div class="text-3xl font-bold gradient-text mb-1">
            {{ stat.value }}
          </div>
          <div class="text-sm text-gray-400">{{ stat.label }}</div>
        </div>
      }
    </div>
  </div>
</section>
