// src/app/components/ui/glass-card/glass-card.component.ts
import { Component, Input } from '@angular/core';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-glass-card',
  standalone: true,
  imports: [NgClass],
  template: `
    <div
      class="glass rounded-2xl overflow-hidden transition-all duration-300"
      [ngClass]="{
        'glass-hover cursor-pointer hover:-translate-y-1 hover:scale-[1.02]': hover,
        'glow': glow
      }"
    >
      <ng-content />
    </div>
  `,
})
export class GlassCardComponent {
  @Input() hover = true;
  @Input() glow = false;
}

// src/components/ui/GlassCard.jsx
import { motion } from 'framer-motion';

export default function GlassCard({ 
  children, 
  className = '', 
  hover = true,
  glow = false,
  as = 'div',
  ...props 
}) {
  const Component = motion[as] || motion.div;
  
  return (
    <Component
      whileHover={hover ? { y: -5, scale: 1.02 } : {}}
      transition={{ duration: 0.3 }}
      className={`
        glass rounded-2xl overflow-hidden
        ${hover ? 'glass-hover cursor-pointer' : ''}
        ${glow ? 'glow' : ''}
        ${className}
      `}
      {...props}
    >
      {children}
    </Component>
  );
}
